### PR TITLE
Review routes

### PR DESCRIPTION
**Pull request by Kalink52**
this branch added the reviews to the products page

I Want everyone to take a look at this. 

it's from a old branch, we merged a lot so most of it should be fine, but i want everyone to double check  to make sure nothing happens

### CODE REVIEW

**Comment by Kalink52** [comment]
I double checked this branch. in my opinion everything should be fine. 👍

**Comment by Kalink52** [comment]
including picture of it pulling reviews from the db
image

**Review by ghost — APPROVED** [review]
Everything checks out, would recommend someone to double check before merging it.

**Review by hannah-finch — APPROVED** [review]
Awesome. I just finished refactoring the update form, and I moved it to its own component, but I'll wait to push that until this is merged cause there'll be conflicts

**Pull request merged**
